package codelens

// DefaultIgnorePatterns default patterns for files to ignore
var DefaultIgnorePatterns = []string{
	// Version control
	".git", ".svn", ".hg",
	".gitignore", ".gitattributes", ".gitmodules", ".gitkeep",
	".hgignore", ".hgtags",
	".bzr", ".bzrignore",
	"CVS", ".cvsignore",
	".repo", ".meta",
	".fossil", ".fossil-settings",
	"SCCS", "RCS",
	".git-blame-ignore-revs",

	// Build and dependency directories
	"node_modules", "vendor", "dist", "build",
	"target", "bin", "obj", "out",
	"packages", "bower_components",
	"jspm_packages", ".pnpm-store",
	".gradle", ".maven", ".m2",
	".nuget", "packages",
	"bazel-*", ".bazelrc",
	"cmake-build-*", "CMakeFiles",
	"Debug", "Release", "x64", "x86",
	"*.xcodeproj", "*.xcworkspace",
	"Pods", "Carthage",
	"*.pbxproj", "*.pbxuser",
	"*.mode1v3", "*.mode2v3",
	"*.perspectivev3", "*.xccheckout",
	"xcuserdata", "*.xcscmblueprint",
	"*.xcuserstate", "*.xcassets",
	"*.storyboard", "*.xib",
	".github",

	// IDEs and editors
	".idea", ".vscode", ".vs",
	"*.swp", "*.swo", "*.swn",
	"*.iml", "*.ipr", "*.iws",
	".project", ".classpath", ".settings",
	"*.sublime-*", "*.atom",
	".history", ".vimrc",
	"*.code-workspace",
	"*.suo", "*.user", "*.userosscache", "*.sln.docstates",
	"*.launch", "*.tmproj",
	".metals", ".bloop",
	"*.workspace", "*.cbp", "*.layout",
	"*.depend", "*.workspace.*",
	"*.njsproj", "*.ntvs*",
	"*.sln.ide", "*.ide",
	"*.csproj.user", "*.vcxproj.user",
	"*.dbmdl", "*.dbproj",
	"*.VC.db", "*.VC.VC.opendb",

	// Temporary files
	"*.tmp", "*.temp", "*.bak",
	".DS_Store", "Thumbs.db", "Desktop.ini",
	"*.log", "*.cache", "*.pid",
	"*.retry", "*.orig",
	"npm-debug.log*", "yarn-debug.log*", "yarn-error.log*",
	".env.*", ".env.local", ".env.development", ".env.test", ".env.production",
	"*.swx", "*~", "*.sw?",
	"Session.vim", "*.vim",
	"*.autosave", "*.backup",
	"core.*", "crash-*",
	".nfs*", ".fuse_hidden*",
	"*.stackdump", "*.core",
	"ehthumbs.db", "ehthumbs_vista.db",
	"[Tt]humbs.db", "[Dd]esktop.ini",
	"$RECYCLE.BIN", "System Volume Information",
	".directory", ".Trash-*",
	".Spotlight-V100", ".Trashes",
	"._*", ".DocumentRevisions-V100",
	".TemporaryItems", ".VolumeIcon.icns",
	".com.apple.timemachine.*",
	".LSOverride", "Icon\r",

	// Binary and executable files
	"*.exe", "*.dll", "*.so", "*.dylib",
	"*.bin", "*.dat", "*.db",
	"*.jar", "*.war", "*.ear",
	"*.app", "*.dmg", "*.iso",
	"*.msi", "*.sys", "*.com",
	"*.lib", "*.a", "*.la", "*.lo",
	"*.pyc", "*.pyo", "*.pyd",
	"*.ko", "*.jnilib",
	"*.framework", "*.bundle",
	"*.ipa", "*.apk", "*.aab",
	"*.deb", "*.rpm", "*.snap",
	"*.xpi", "*.crx", "*.nupkg",
	"*.gem", "*.whl", "*.msi",
	"*.pkg", "*.appxbundle",
	"*.dylib.dSYM", "*.so.dSYM",
	"*.dll.config", "*.so.*",

	// Compressed files
	"*.zip", "*.rar", "*.7z", "*.gz", "*.tar",
	"*.tgz", "*.bz2", "*.xz",
	"*.jar", "*.war", "*.ear",
	"*.pkg", "*.deb", "*.rpm",
	"*.cab", "*.msix", "*.appx",
	"*.sit", "*.sitx", "*.hqx",
	"*.lz", "*.lz4", "*.lzma",
	"*.zst", "*.br", "*.sz",
	"*.ace", "*.arj", "*.lha",
	"*.alz", "*.arc", "*.zoo",
	"*.cpio", "*.rz", "*.lrz",
	"*.pak", "*.z", "*.Z",

	// Media files
	"*.jpg", "*.jpeg", "*.png", "*.gif", "*.ico",
	"*.mp3", "*.mp4", "*.avi", "*.mov",
	"*.wav", "*.flac", "*.ogg",
	"*.webm", "*.mkv", "*.wmv",
	"*.svg", "*.eps", "*.psd",
	"*.ttf", "*.eot", "*.woff", "*.woff2",
	"*.pdf", "*.doc", "*.docx",
	"*.xls", "*.xlsx", "*.ppt", "*.pptx",
	"*.heic", "*.heif", "*.raw",
	"*.ai", "*.indd", "*.sketch",
	"*.afdesign", "*.afphoto",
	"*.tiff", "*.bmp", "*.webp",
	"*.m4a", "*.aac", "*.midi",
	"*.mobi", "*.epub", "*.azw",
	"*.cr2", "*.nef", "*.arw",
	"*.dng", "*.orf", "*.rw2",
	"*.3gp", "*.m4v", "*.mpg",
	"*.mpeg", "*.mpe", "*.vob",
	"*.asf", "*.rm", "*.rmvb",
	"*.mid", "*.kar", "*.m3u",
	"*.wma", "*.mka", "*.ra",
	"*.aif", "*.aifc", "*.aiff",
	"*.snd", "*.au", "*.cda",

	// Language specific
	"__pycache__", ".pytest_cache",
	"node_modules", "bower_components",
	"vendor", "packages",
	".bundle", ".vendor",
	".cargo", "target",

	// Package lock files
	"package-lock.json", "yarn.lock", "pnpm-lock.yaml",
	"npm-shrinkwrap.json", "bun.lockb",
	"Gemfile.lock", "Cargo.lock",
	"poetry.lock", "pdm.lock",
	"mix.lock", "deps.ts",
	"pnpm-workspace.yaml", "lerna.json",
	"rush.json", "bower.json",
	"composer.lock", "Pipfile.lock",
	"requirements.txt", "go.sum",
	"gradle.lockfile", "gradle/dependency-locks/*",
	"yarn.lock.yaml", "shrinkwrap.yaml",
	"flake.lock", "deno.lock",
	"Podfile.lock", "pubspec.lock",
	"Package.resolved", "paket.lock",
	"packages.lock.json", "project.lock.json",

	"*.test", "*.out", "*.prof",
	"*.race", "*.trace", "*.cover",
	"*.rlib", "*.rmeta", "*.d",
	"*.class", "*.jar", "*.war",
	"*.ear", "*.nar", "*.jpi",
	"*.pyc", "*.pyo", "*.pyd",
	"*.so", "*.egg", "*.egg-info",
	"*.node", "*.npm", "*.yarn",
	"*.gem", "*.rbc", ".rspec",
	"*.phar", "composer.phar",
	"*.pdb", "*.cache", "*.resources",
	"*.deploy", "*.rdl.data",
}
